[project]
name = "amuse-uclchem"
version = "0.0.1"
# use the line below instead of the version above if this code is inside the AMUSE
# repository
# dynamic = ["version"]
requires-python = ">=3.7"
dependencies = [
    "amuse-framework==2025.9.1.dev3+gce21df1cc"
]

[build-system]
requires = ["hatchling", "versioningit"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "versioningit"

[tool.versioningit.next-version]
method = "smallest"

[tool.versioningit.format]
distance = "{next_version}.dev{distance}+{vcs}{rev}"
dirty = "{base_version}+d{build_date:%Y%m%d}"
distance-dirty = "{next_version}.dev{distance}+{vcs}{rev}.d{build_date:%Y%m%d}"

[tool.versioningit.vcs]
method = { module = "version_helper", value = "get_amuse_version", module-dir = "amuse_uclchem/support/shared" }

[tool.hatch.build]
skip-excluded-dirs = true

[tool.hatch.build.targets.wheel]
include = ["amuse_uclchem/**/*.py"]
exclude = [
    "amuse_uclchem/packages",
    "amuse_uclchem/support",
    "amuse_uclchem/src",
    "amuse_uclchem/tests"
    ]
artifacts = ["amuse_uclchem/uclchem_worker"]

[tool.pytest.ini_options]
pythonpath = ["amuse_uclchem/tests/"]

testpaths = ["amuse_uclchem/tests"]

